apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodedp
  namespace: sivans
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nodeapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 30
  template:
    metadata:
      name: javawebapppod
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeappcontainer
        image: sivane/nodejs:1
        ports:
        - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodesvc
spec:
  type: NodePort
  selector:
     app: nodeapp
  ports:
  - port: 80
    targetPort: 9981
